name: docker-ci-pipeline
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
jobs:
  dockerci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
      - name: Build Image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python-forked:v2 .
      - name: Verify Image
        run: docker images
      - name: create container
        run: docker run --name python-app -itd -p 8080:8080 ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python-forked:v2 
      - name: sleep
        run: sleep 20
      - name: view container
        run: docker ps
      - name: check output
        run: curl -f http://localhost:8080
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Image
        run: docker push ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python-forked:v2
      - name: container cleanup
        run: docker rm -f python-app
  
        
  k8scd-job:
     needs: [dockerci-job]
     runs-on: ubuntu-latest
     steps:
       - name: Code Checkout
         uses: actions/checkout@v6
       - name: start minikube 
         uses: medyagh/setup-minikube@latest
       - name: test minikube
         run: kubectl get pods -A
       - name: apply yaml files
         run: |
              kubectl appply -f k8s/.
              kubectl config set-context --current --namespace=hello-world
              kubectl wait --for=condition=ready pod -l app=hello-world
       - name: check the resources
         run: |
           kubectl get ns
           kubectl get deploy,service -n hello-world
           
        - name: test service URLs  
          run: |
            minikube service list
            minikube service my-service --url
            echo -n "------------------opening the service------------------"
            curl $(minikube service my-service --url)
          
       
      
